- name: Install Gitlab dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - openssh-server
      - postfix
    state: present
  become: true

- name: Add GitLab repository
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
  become: true

- name: Install GitLab
  apt:
    name: gitlab-ce
    state: present
  become: true

- name: Configure GitLab
  shell: gitlab-ctl reconfigure
  become: true

- name: Configure GitLab domain
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url'
    line: "external_url 'http://{{ gitlab_domain }}'"
  notify: Restart GitLab
  become: yes

- name: Configure GitLab storage path
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^git_data_dirs'
    line: 'git_data_dirs({"default" => {"path" => "{{ gitlab_storage_path }}"}})'
  notify: Restart GitLab
  become: yes

